name: relase

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required: GitHub OIDC token issuance for trusted publishing
      contents: read # required: read access to the repository contents

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Get the release on the same checks as CI before anything is published
      - name: restore
        run: dotnet restore cqrs-scaffolding.sln

      - name: Build
        run: dotnet build cqrs-scaffolding.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test cqrs-scaffolding.sln --no-build --configuration Release --nologo

      - name: Pack
        run: >
          dotnet pack src/CqrsScaffold.Tool/CqrsScaffold.Tool.csproj --no-build --configuration Release

      - name: Nuget login (OIDC -> temp API key)
        uses: nuget/setup-nuget@v1
        id: login
        with:
          user: ${{ github.NUGET_USER }} # nuget.org profile name, not email
          
      - name: Publish
        run: dotnet nuget push src/CqrsScaffold.Tool/bin/Release/CqrsScaffold.Tool.*.nupkg --api-key ${{ steps.login.outputs.api-key }} --source https://api.nuget.org/v3/index.json --skip-duplicate